version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  sidekiq-cache:
    image: redis:7.0.2
    command: redis-server
  sidekiq:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
    environment:
      - REDIS_URL=redis://sidekiq-cache:6379/0
    volumes:
      - .:/myapp
    depends_on:
      - db
      - sidekiq-cache
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_URL=redis://sidekiq-cache:6379/0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq-cache
